name: Bot Final SystemaTrader

on:
  schedule:
    # Horarios UTC (Lunes a Viernes)
    # 14:30 UTC = 09:30 AM NY (Apertura)
    # 17:00 UTC = 12:00 PM NY (Medio d√≠a)
    # 20:00 UTC = 03:00 PM NY (Cerca del Cierre)
    - cron: '30 14 * * 1-5'
    - cron: '0 17 * * 1-5'
    - cron: '0 20 * * 1-5'
  workflow_dispatch:

jobs:
  ejecutar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Instalar Dependencias
        run: |
          pip install "numpy<2.0.0"
          pip install pandas==1.3.5
          pip install yfinance requests

      - name: Correr Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python alerta_bot.py
