name: Bot Final SystemaTrader

on:
  schedule:
    - cron: '0 14 * * 1-5'
    - cron: '0 17 * * 1-5'
    - cron: '30 20 * * 1-5'
  workflow_dispatch:

jobs:
  ejecutar_bot:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar Código
        uses: actions/checkout@v3

      - name: Instalar Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Librerías (Manual)
        # Instalamos linea por linea para evitar errores
        run: |
          pip install --upgrade pip
          pip install numpy==1.23.5
          pip install pandas==1.5.3
          pip install yfinance
          pip install requests
          pip install pandas_ta

      - name: Correr Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        # Aseguramos que el nombre del archivo sea el correcto
        run: python alerta_bot.py
